language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
